# Background and foreground colors
background = #000000
foreground = #ffffff

# Standard colors
palette = 0=#000000
palette = 1=#ea385e
palette = 2=#41c86b
palette = 3=#FFBA49
palette = 4=#8274fd
palette = 5=#ea385e
palette = 6=#2ab6fb
palette = 7=#ffffff

# Bright colors
palette = 8=#595959
palette = 9=#ee5e7c
palette = 10=#75d793
palette = 11=#ffce80
palette = 12=#8e82fd
palette = 13=#ee5e7c
palette = 14=#50c3fc
palette = 15=#f1f1f1
