background            #000000
foreground            #ffffff

# black
color0  #000000
color8  #595959

# red
color1  #ea385e
color9  #ee5e7c

# green
color2  #41c86b
color10 #75d793

# yellow
color3  #FFBA49
color11 #ffce80

# blue
color4  #8274fd
color12 #8e82fd

# magenta
color5  #ea385e
color13 #ee5e7c

#cyan
color6  #2ab6fb
color14 #50c3fc

#white
color7  #ffffff
color15 #f1f1f1


